### ISSUE TITLE
AttributeError: 'Context' object has no attribute 'add_reaction'

### ISSUE THREAD

**Issue by Motzumoto** [Gorialis/jishaku#219]
## Summary
running jsk debug errors. Its unable to add a reaction to the message. However jsk py adds the reaction just fine. 
![image](https://github.com/Gorialis/jishaku/assets/45925152/9e592f28-80c6-46fb-8232-a125ec599a52)

## Reproduction steps
jsk debug and then anything else.

## Expected results
add the reaction successfully like jsk py

## Actual results
Errors

## Checklist

- [x] I have updated discord.py and jishaku to the latest available versions and have confirmed that this issue is still present
- [x] I have searched the open issues for duplicates
- [x] I have shown the entire traceback, if possible
- [x] I have removed my token from display, if visible

## System information

Name: jishaku
Version: 2.5.2a485+g32009b4.master
Summary: A discord.py extension including useful tools for bot development and debugging.
Home-page: https://github.com/Gorialis/jishaku
Author: Devon (Gorialis) R
Author-email: 
License: MIT
Location: /home/container/.local/lib/python3.10/site-packages
Requires: braceexpand, click, import-expression, tabulate
Required-by: 

Name: discord.py
Version: 2.3.2
Summary: A Python wrapper for the Discord API
Home-page: https://github.com/Rapptz/discord.py
Author: Rapptz
Author-email: 
License: MIT
Location: /home/container/.local/lib/python3.10/site-packages
Requires: aiohttp
Required-by: discord-ext-menus, wavelink

**Comment by Gorialis** [comment]
caused by changes introduced in #218, need to revert that bit

**Comment by Gorialis** [comment]
This was fixed in #220 and I forgot to close this.
